name: Android CI

on:
  push:
    branches: [ "main", "33-set-up-ci" ]
    # TODO: Remove the second branch after testing

jobs:
  build:
    runs-on: [github-runner, Linux, X64]
    steps:
    - uses: actions/checkout@v4

    - name: Set up ADB
      uses: android-actions/setup-android@v3.2.1

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Connect to emulator
      run: adb connect localhost:5555

    - name: Wait for emulator
      run: adb wait-for-device

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Run UI tests
      run: ./gradlew connectedDebugAndroidTest

    # In the future, we can add steps to push the built apk to GitHub here
